export { default as authRouter } from './auth.ts';
export { default as userRouter } from './user.ts';
export { default as activityRouter } from './activity.ts';
export { default as favoriteRouter } from './favorite.ts';
export { default as eventRouter } from './event.ts';
export { default as categoryRouter } from './category.ts';
export { default as beratungRouter } from './beratung.ts';
export { default as chatRouter } from './chatbot.ts';
export { default as vocabularyRouter } from './vocabulary.ts';
